In [1]:
import numpy as np

In [11]:
x = [["1", "b", "c", "d", "5"], ["1", "b", "c", "d", "6"]]
y = [["1", "b", "c", "d", "5"], ["1", "b", "c", "d", "6"]]

In [12]:
a = np.array(x)
b = np.array(y)

In [14]:
np.vstack([a, b])

array([['1', 'b', 'c', 'd', '5'],
       ['1', 'b', 'c', 'd', '6'],
       ['1', 'b', 'c', 'd', '5'],
       ['1', 'b', 'c', 'd', '6']], dtype='<U1')

In [15]:
import numpy as np

def filter_data_by_tags(data, tags, tag_list):
    tag_set = set(tag_list)

    # Create a boolean mask where True indicates the tag is in tag_list
    mask = np.isin(tags, list(tag_set))

    # Use the mask to filter the data and tags arrays
    filtered_data = data[mask]
    filtered_tags = tags[mask]

    return filtered_data, filtered_tags

# Example usage
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tags = np.array(['a', 'b', 'a', 'c'])
tag_list = ['a', 'c']

filtered_data, filtered_tags = filter_data_by_tags(data, tags, tag_list)

print("Filtered data:")
print(filtered_data)

print("Filtered tags:")
print(filtered_tags)


Filtered data:
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]
Filtered tags:
['a' 'a' 'c']


In [16]:
a, b = ["1", "2"]