In [1]:
from C_0Q_run import load_dict
import os
from paths import *

In [2]:
load_dict()

['BLANK',
 'SIL',
 'AE',
 'AO',
 'AA',
 'IH',
 'ER',
 'Y',
 'EH',
 'OY',
 'UH',
 'P',
 'AW',
 'UW',
 'EY',
 'T',
 'IY',
 'K',
 'AY',
 'OW',
 'AH',
 'S',
 'Ph',
 'Th',
 'Kh']

In [3]:
load_dict(os.path.join(src_, "phi-seg.dict"))

['BLANK',
 'SIL',
 'AE',
 'AO',
 'AA',
 'IH',
 'ER',
 'Y',
 'EH',
 'OY',
 'UH',
 'P',
 'AW',
 'UW',
 'EY',
 'T',
 'IY',
 'K',
 'AY',
 'OW',
 'AH',
 'S',
 'Ph',
 'Th',
 'Kh']

In [5]:
import numpy as np
import random

def separate_and_sample_data(data_array, tag_array, sample_num):
    # Ensure data_array and tag_array are numpy arrays
    data_array = np.array(data_array)
    tag_array = np.array(tag_array)
    
    # Create a dictionary to store data based on tags
    tag_data_dict = {}
    
    # Iterate over the data and tags to separate them
    for data, tag in zip(data_array, tag_array):
        if tag not in tag_data_dict:
            tag_data_dict[tag] = []
        tag_data_dict[tag].append(data)
    
    # Create a list to store the numpy arrays for each tag
    sampled_data_arrays = []
    sampled_tags = []
    
    # Iterate over the tag_data_dict to sample the data
    for tag, data_list in tag_data_dict.items():
        # Shuffle the data list
        random.shuffle(data_list)
        # Take the specified number of samples
        samples = data_list[:sample_num]
        # Convert the samples to a numpy array and add to the result list
        sampled_data_arrays.append(np.array(samples))
        sampled_tags.append(tag)
    
    return sampled_data_arrays, sampled_tags

# Example usage
data_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tag_array = np.array(['A', 'A', 'B', 'B', 'C', 'C', 'A', 'B', 'C', 'A'])
sample_num = 2

sampled_data_arrays, sampled_tags = separate_and_sample_data(data_array, tag_array, sample_num)
for tag, arr in zip(sampled_tags, sampled_data_arrays):
    print(f"Sampled Data for tag {tag}:", arr)


Sampled Data for tag A: [7 2]
Sampled Data for tag B: [4 3]
Sampled Data for tag C: [9 5]


In [6]:
sampled_tags

['A', 'B', 'C']

In [9]:
def filter_data_by_tags(data, tags, select):
    # Convert tag_list to a set for faster membership testing
    tag_set = set(select)

    # Create a boolean mask where True indicates the tag is in tag_list
    mask = np.isin(tags, list(tag_set))

    # Use the mask to filter the data and tags arrays
    filtered_data = data[mask]
    filtered_tags = tags[mask]

    return filtered_data, filtered_tags

In [14]:
data_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tag_array = np.array(['A', 'A', 'B', 'B', 'C', 'C', 'A', 'B', 'C', 'A'])

In [15]:
def separate_and_sample_data(data_array, tag_array, sample_size):
    # Ensure data_array and tag_array are numpy arrays
    data_array = np.array(data_array)
    tag_array = np.array(tag_array)
    tags = np.unique(tag_array)
    data_list = []
    tag_list = []
    for tag in tags: 
        filtered_data, filtered_tag = filter_data_by_tags(data_array, tag_array, tag)
        indices = np.random.choice(len(filtered_data), size=sample_size, replace=(sample_size > len(filtered_data)))
        selected_data = filtered_data[indices]
        selected_tag = filtered_tag[indices]
        data_list.append(selected_data)
        tag_list.append(selected_tag)
    return data_list, tag_list

In [18]:
separate_and_sample_data(data_array, tag_array, 5)

([array([ 2,  7, 10,  2,  1]), array([3, 3, 3, 4, 4]), array([9, 5, 9, 5, 9])],
 [array(['A', 'A', 'A', 'A', 'A'], dtype='<U1'),
  array(['B', 'B', 'B', 'B', 'B'], dtype='<U1'),
  array(['C', 'C', 'C', 'C', 'C'], dtype='<U1')])

In [19]:
import numpy as np

# Example array of shape (run, e, rep)
array = np.random.rand(4, 3, 2)  # Example dimensions, replace with your actual dimensions

# Reshape the array
reshaped_array = array.transpose(0, 2, 1).reshape(-1, array.shape[1])

print("Original array shape:", array.shape)
print("Reshaped array shape:", reshaped_array.shape)
print("Reshaped array:\n", reshaped_array)


Original array shape: (4, 3, 2)
Reshaped array shape: (8, 3)
Reshaped array:
 [[0.02521685 0.71435663 0.95357981]
 [0.38029638 0.94505827 0.26817545]
 [0.64866417 0.90751782 0.1139863 ]
 [0.99339275 0.86356921 0.18888309]
 [0.89208779 0.908706   0.86353659]
 [0.90969781 0.48239495 0.01755373]
 [0.85875399 0.16580447 0.53319592]
 [0.64257455 0.81657396 0.01052604]]


In [7]:
import torch
import torch.nn as nn

In [5]:
outputs = []
dec_x = torch.tensor([1.0])

for _ in range(3):
    outputs.append(dec_x.clone().detach())
    dec_x += 1  # Modify dec_x


In [6]:
outputs

[tensor([1.]), tensor([2.]), tensor([3.])]

In [10]:
outputs = []
dec_x = torch.tensor([1.0])
lin = nn.Linear(1, 1)

for _ in range(3):
    outputs.append(dec_x)
    dec_x = lin(dec_x)  # Modify dec_x


In [31]:
lin1 = nn.Linear(1, 1)
lin2 = nn.Linear(1, 1)

In [37]:
def fun(x, y): 
    x = x + 1
    y = lin2(y)
    return x + y

In [38]:
dec_x = torch.tensor([1.0])

In [39]:
k = fun(dec_x, dec_x)

In [40]:
dec_x

tensor([1.])

In [41]:
k

tensor([1.0752], grad_fn=<AddBackward0>)

In [27]:
dec_x = torch.tensor([1.0])

outputs = []
for _ in range(3):
    fun(dec_x.clone())
    outputs.append(dec_x)
    dec_x += 1

In [28]:
outputs

[tensor([4.]), tensor([4.]), tensor([4.])]

In [42]:
from model_attention import ScaledDotProductAttention

In [57]:
attn = ScaledDotProductAttention(2, 2, 2, 2)

In [90]:
dec_x = torch.randn(2, 3, 2)
hid_r = torch.randn(2, 3, 2)

In [91]:
dec_x, hid_r

(tensor([[[-0.0826, -0.0035],
          [ 2.0388, -1.0152],
          [ 0.1554,  0.1011]],
 
         [[-0.6186, -0.8835],
          [ 0.0358,  0.1771],
          [ 1.3495,  0.3323]]]),
 tensor([[[-1.3553,  0.7411],
          [-0.5815, -0.9433],
          [ 1.5289,  1.2274]],
 
         [[ 1.3136,  1.4699],
          [-1.2667, -0.4441],
          [-0.1843,  1.4859]]]))

In [92]:
dl = []
al = []
for i in range(3): 
    dec_x, attention_weight = attn(dec_x, hid_r, hid_r)
    dl.append(dec_x.clone().detach())
    print(dec_x)
    al.append(attention_weight.clone().detach())

tensor([[[-0.0959,  0.0451],
         [-0.3224, -0.0294],
         [-0.1105,  0.0406]],

        [[-0.3387, -0.0503],
         [-0.3297, -0.0461],
         [-0.4428, -0.0839]]], grad_fn=<BmmBackward0>)
tensor([[[-0.0921,  0.0465],
         [-0.0771,  0.0513],
         [-0.0911,  0.0468]],

        [[-0.3079, -0.0389],
         [-0.3085, -0.0391],
         [-0.2996, -0.0361]]], grad_fn=<BmmBackward0>)
tensor([[[-0.0923,  0.0464],
         [-0.0934,  0.0461],
         [-0.0924,  0.0464]],

        [[-0.3102, -0.0397],
         [-0.3102, -0.0396],
         [-0.3109, -0.0399]]], grad_fn=<BmmBackward0>)


In [93]:
dl

[tensor([[[-0.0959,  0.0451],
          [-0.3224, -0.0294],
          [-0.1105,  0.0406]],
 
         [[-0.3387, -0.0503],
          [-0.3297, -0.0461],
          [-0.4428, -0.0839]]]),
 tensor([[[-0.0921,  0.0465],
          [-0.0771,  0.0513],
          [-0.0911,  0.0468]],
 
         [[-0.3079, -0.0389],
          [-0.3085, -0.0391],
          [-0.2996, -0.0361]]]),
 tensor([[[-0.0923,  0.0464],
          [-0.0934,  0.0461],
          [-0.0924,  0.0464]],
 
         [[-0.3102, -0.0397],
          [-0.3102, -0.0396],
          [-0.3109, -0.0399]]])]

In [72]:
al

[tensor([[[0.4259, 0.1878, 0.3863],
          [0.4259, 0.1878, 0.3863],
          [0.4259, 0.1878, 0.3863]],
 
         [[0.4100, 0.3243, 0.2657],
          [0.4100, 0.3243, 0.2657],
          [0.4101, 0.3240, 0.2659]]]),
 tensor([[[0.4259, 0.1878, 0.3863],
          [0.4259, 0.1878, 0.3863],
          [0.4259, 0.1878, 0.3863]],
 
         [[0.4100, 0.3243, 0.2657],
          [0.4100, 0.3243, 0.2657],
          [0.4100, 0.3243, 0.2657]]]),
 tensor([[[0.4259, 0.1878, 0.3863],
          [0.4259, 0.1878, 0.3863],
          [0.4259, 0.1878, 0.3863]],
 
         [[0.4100, 0.3243, 0.2657],
          [0.4100, 0.3243, 0.2657],
          [0.4100, 0.3243, 0.2657]]])]

In [58]:
dec_x = torch.randn(2, 3, 2)
hid_r = torch.randn(2, 3, 2)

In [60]:
hid_r

tensor([[[ 0.3325,  1.3512],
         [ 0.2701, -0.6283],
         [-1.8334, -0.3375]],

        [[-1.4090, -0.6623],
         [-1.8631,  0.6772],
         [ 0.0529, -0.3842]]])

In [61]:
dec_x, attention_weight = attn(dec_x, hid_r, hid_r)

In [62]:
dec_x, hid_r

(tensor([[[-0.0337,  0.0652],
          [ 0.1152,  0.1198],
          [ 0.0183,  0.0807]],
 
         [[ 0.3165,  0.1622],
          [ 0.2981,  0.1501],
          [ 0.3118,  0.1573]]], grad_fn=<BmmBackward0>),
 tensor([[[ 0.3325,  1.3512],
          [ 0.2701, -0.6283],
          [-1.8334, -0.3375]],
 
         [[-1.4090, -0.6623],
          [-1.8631,  0.6772],
          [ 0.0529, -0.3842]]]))